public with sharing class createLeadLWC {
    @AuraEnabled
    public static void insertLead(List<Lead> leadList) {
////        for (List<Opportunity> oppts:
////        [SELECT Id, Name, Amount, StageName, CloseDate FROM Opportunity WHERE Amount > :amount]) {
////            for(Opportunity o : oppts) {
////                o.StageName = stage;
////            }
////            update oppts;
////        }
////        return;
    }
}